script changed

diff --git a/.github/workflows/tracker.yml b/.github/workflows/tracker.yml
--- a/.github/workflows/tracker.yml
+++ b/.github/workflows/tracker.yml
@@ -34,11 +34,21 @@ jobs:
         sudo mv geckodriver /usr/local/bin/
         rm geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
 
+    - name: Check for config.json
+      run: |
+        if [ -f config.json ]; then
+          echo "config.json found."
+        else
+          echo "config.json not found."
+          exit 1
+        fi
+
     - name: Upload JSON config
       uses: actions/upload-artifact@v3
       with:
         name: config
         path: config.json
+        if-no-files-found: warn
 
     - name: Run price_tracker.py
       run: python price_tracker.py
