script changed

diff --git a/.github/workflows/tracker.yml b/.github/workflows/tracker.yml
--- a/.github/workflows/tracker.yml
+++ b/.github/workflows/tracker.yml
@@ -26,43 +26,33 @@ jobs:
         sudo apt-get install -y google-chrome-stable
 
     - name: Check Chrome Version
-  run: |
-    CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
-    echo "Chrome Version: $CHROME_VERSION"
-    CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
-    echo "Chrome Major Version: $CHROME_MAJOR_VERSION"
-    echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
-    echo "CHROME_MAJOR_VERSION=$CHROME_MAJOR_VERSION" >> $GITHUB_ENV
-
-- name: Install ChromeDriver
-  run: |
-    CHROME_MAJOR_VERSION=$(echo $CHROME_MAJOR_VERSION)
-    echo "Using Major Version: $CHROME_MAJOR_VERSION"
-    CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
-    echo "ChromeDriver Version: $CHROMEDRIVER_VERSION"
-    if [ -z "$CHROMEDRIVER_VERSION" ]; then
-      echo "Failed to get ChromeDriver version"
-      exit 1
-    fi
-    wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
-    unzip chromedriver_linux64.zip -d $HOME/bin
-    rm chromedriver_linux64.zip
-    chmod +x $HOME/bin/chromedriver
-    export PATH=$HOME/bin:$PATH
-
-
-    - name: Set environment variables from JSON
       run: |
-        FROM_EMAIL=$(jq -r '.FROM_EMAIL' config.json)
-        EMAIL_PASSWORD=$(jq -r '.EMAIL_PASSWORD' config.json)
-        TO_EMAIL=$(jq -r '.TO_EMAIL' config.json)
-        echo "FROM_EMAIL=$FROM_EMAIL" >> $GITHUB_ENV
-        echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> $GITHUB_ENV
-        echo "TO_EMAIL=$TO_EMAIL" >> $GITHUB_ENV
+        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
+        echo "Chrome Version: $CHROME_VERSION"
+        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
+        echo "Chrome Major Version: $CHROME_MAJOR_VERSION"
+        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
+        echo "CHROME_MAJOR_VERSION=$CHROME_MAJOR_VERSION" >> $GITHUB_ENV
+
+    - name: Install ChromeDriver
+      run: |
+        CHROME_MAJOR_VERSION=$(echo $CHROME_MAJOR_VERSION)
+        echo "Using Major Version: $CHROME_MAJOR_VERSION"
+        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
+        echo "ChromeDriver Version: $CHROMEDRIVER_VERSION"
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Failed to get ChromeDriver version"
+          exit 1
+        fi
+        wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
+        unzip chromedriver_linux64.zip -d $HOME/bin
+        rm chromedriver_linux64.zip
+        chmod +x $HOME/bin/chromedriver
+        export PATH=$HOME/bin:$PATH
 
     - name: Run price_tracker.py
       run: python price_tracker.py
       env:
-        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
-        EMAIL_TO: ${{ secrets.EMAIL_TO }}
+        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
         EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
+        TO_EMAIL: ${{ secrets.TO_EMAIL }}
